import { createSlice } from "@reduxjs/toolkit";

export const rooms = [
  {
    id: 1,
    title: "Beach villa",
    price: 100,
    images: [
      "/images/room1-img1.jpg",
      "/images/room1-img2.jpg",
      "/images/room1-img3.jpg",
    ],
    amenities: [
      "220V electrical sockets",
      "36-inch LCD TV",
      "Bathrobe",
      "Complimentary toiletries",
      "Emergency lighting",
      "Hair-dryer",
      "Individual climate control",
      "Multimedia hub",
      "Ocean view",
      "Refrigerator",
      "Safety box",
      "Satellite channels",
      "Shower",
      "Smoke alarms",
      "Wifi",
    ],
    available: [Date.now(), new Date("2023-12-31").getTime()],
  },
  {
    id: 2,
    title: "Beach villa",
    price: 165,
    images: [
      "/images/room2-img1.jpg",
      "/images/room2-img2.jpg",
      "/images/room2-img3.jpg",
    ],
    amenities: [
      "260V electrical sockets",
      "44-inch LCD TV",
      "Bathrobe",
      "Clothes line",
      "Complimentary toiletries",
      "Emergency lighting",
      "Hair-dryer",
      "Individual climate control",
      "Ironing facilities",
      "Mini bar",
      "Multimedia hub",
      "Ocean view",
      "Refrigerator",
      "Safety box",
      "Satellite channels",
      "Shower",
      "Slippers",
      "Smoke alarms",
      "Tea and coffee making",
      "Wifi",
      "Work desk",
    ],
    available: [Date.now(), new Date("2023-11-15").getTime()],
  },
  {
    id: 3,
    title: "Classic single bed",
    price: 155,
    images: [
      "/images/room3-img1.jpg",
      "/images/room3-img2.jpg",
      "/images/room3-img3.jpg",
    ],
    amenities: [
      "240V electrical sockets",
      "40-inch LCD TV",
      "Bathrobe",
      "Complimentary toiletries",
      "Emergency lighting",
      "Hair-dryer",
      "Individual climate control",
      "Ironing facilities",
      "Mini bar",
      "Multimedia hub",
      "Ocean view",
      "Refrigerator",
      "Safety box",
      "Satellite channels",
      "Shower",
      "Slippers",
      "Smoke alarms",
      "Tea and coffee making",
      "Wifi",
    ],
    available: [Date.now(), new Date("2023-11-30").getTime()],
  },
  {
    id: 4,
    title: "Contemporary suites",
    price: 130,
    images: [
      "/images/room4-img1.jpg",
      "/images/room4-img2.jpg",
      "/images/room4-img3.jpg",
    ],
    amenities: [
      "220V electrical sockets",
      "38-inch LCD TV",
      "Bathrobe",
      "Complimentary toiletries",
      "Emergency lighting",
      "Hair-dryer",
      "Individual climate control",
      "Ironing facilities",
      "Mini bar",
      "Multimedia hub",
      "Ocean view",
      "Refrigerator",
      "Safety box",
      "Satellite channels",
      "Shower",
      "Slippers",
      "Smoke alarms",
      "Tea and coffee making",
      "Wifi",
    ],
    available: [Date.now(), new Date("2023-11-30").getTime()],
  },
  {
    id: 5,
    title: "Double Room",
    price: 145,
    images: [
      "/images/room5-img1.jpg",
      "/images/room5-img2.jpg",
      "/images/room5-img3.jpg",
      "/images/room5-img4.jpg",
    ],
    amenities: [
      "220V electrical sockets",
      "42-inch LCD TV",
      "Bathrobe",
      "Clothes line",
      "Complimentary toiletries",
      "Emergency lighting",
      "Hair-dryer",
      "Individual climate control",
      "Ironing facilities",
      "Mini bar",
      "Multimedia hub",
      "Ocean view",
      "Refrigerator",
      "Safety box",
      "Satellite channels",
      "Shower",
      "Slippers",
      "Smoke alarms",
      "Tea and coffee making",
      "Wifi",
      "Work desk",
    ],
    available: [Date.now(), new Date("2023-12-15").getTime()],
  },
  {
    id: 6,
    title: "Double Room",
    price: 160,
    images: [
      "/images/room6-img1.jpg",
      "/images/room6-img2.jpg",
      "/images/room6-img3.jpg",
    ],
    amenities: [
      "220V electrical sockets",
      "42-inch LCD TV",
      "Bathrobe",
      "Clothes line",
      "Complimentary toiletries",
      "Emergency lighting",
      "Hair-dryer",
      "Individual climate control",
      "Ironing facilities",
      "Mini bar",
      "Multimedia hub",
      "Ocean view",
      "Refrigerator",
      "Safety box",
      "Satellite channels",
      "Shower",
      "Slippers",
      "Smoke alarms",
      "Tea and coffee making",
      "Wifi",
      "Work desk",
    ],
    available: [Date.now(), new Date("2023-12-10").getTime()],
  },
  {
    id: 7,
    title: "Excutive suites",
    price: 185,
    images: [
      "/images/room7-img1.jpg",
      "/images/room7-img2.jpg",
      "/images/room7-img3.jpg",
    ],
    amenities: [
      "260V electrical sockets",
      "54-inch LCD TV",
      "Bathrobe",
      "Clothes line",
      "Complimentary toiletries",
      "Emergency lighting",
      "Hair-dryer",
      "Individual climate control",
      "Ironing facilities",
      "Mini bar",
      "Multimedia hub",
      "Ocean view",
      "Refrigerator",
      "Safety box",
      "Satellite channels",
      "Shower",
      "Slippers",
      "Smoke alarms",
      "Tea and coffee making",
      "Wifi",
      "Work desk",
    ],
    available: [Date.now(), new Date("2023-12-31").getTime()],
  },
  {
    id: 8,
    title: "Excutive suites",
    price: 180,
    images: [
      "/images/room8-img1.jpg",
      "/images/room8-img2.jpg",
      "/images/room8-img3.jpg",
    ],
    amenities: [
      "260V electrical sockets",
      "54-inch LCD TV",
      "Bathrobe",
      "Clothes line",
      "Complimentary toiletries",
      "Emergency lighting",
      "Hair-dryer",
      "Individual climate control",
      "Ironing facilities",
      "Mini bar",
      "Multimedia hub",
      "Ocean view",
      "Refrigerator",
      "Safety box",
      "Satellite channels",
      "Shower",
      "Slippers",
      "Smoke alarms",
      "Tea and coffee making",
      "Wifi",
      "Work desk",
    ],
    available: [Date.now(), new Date("2023-12-10").getTime()],
  },
  {
    id: 9,
    title: "Junior suite",
    price: 130,
    images: [
      "/images/room9-img1.jpg",
      "/images/room9-img2.jpg",
      "/images/room9-img3.jpg",
    ],
    amenities: [
      "220V electrical sockets",
      "40-inch LCD TV",
      "Bathrobe",
      "Complimentary toiletries",
      "Emergency lighting",
      "Hair-dryer",
      "Individual climate control",
      "Multimedia hub",
      "Ocean view",
      "Refrigerator",
      "Safety box",
      "Satellite channels",
      "Shower",
      "Smoke alarms",
      "Tea and coffee making",
      "Wifi",
    ],
    available: [Date.now(), new Date("2023-11-20").getTime()],
  },
  {
    id: 10,
    title: "Junior suite",
    price: 140,
    images: [
      "/images/room10-img1.jpg",
      "/images/room10-img2.jpg",
      "/images/room10-img3.jpg",
    ],
    amenities: [
      "220V electrical sockets",
      "44-inch LCD TV",
      "Bathrobe",
      "Complimentary toiletries",
      "Emergency lighting",
      "Hair-dryer",
      "Individual climate control",
      "Multimedia hub",
      "Ocean view",
      "Refrigerator",
      "Safety box",
      "Satellite channels",
      "Shower",
      "Smoke alarms",
      "Tea and coffee making",
      "Wifi",
    ],
    available: [Date.now(), new Date("2023-11-30").getTime()],
  },
];

const searchState = {
  rooms: rooms,
  filteredRooms: JSON.parse(localStorage.getItem("filteredRooms")) || [],
  bookingValues: JSON.parse(localStorage.getItem("bookingValues")) || [],
};

const searchSlice = createSlice({
  name: "search-slice",
  initialState: searchState,
  reducers: {
    filterRooms(state, action) {
      if (action.payload === true) {
        state.filteredRooms = rooms;
      } else
        state.filteredRooms = rooms.filter((room) => {
          return (
            room.available[1] >= action.payload.checkIn &&
            room.available[1] <= action.payload.checkOut
          );
        });

      state.bookingValues = Object.keys(action.payload).map((key) => ({
        key,
        value: action.payload[key],
      }));
    },
    resetChildrenAndAdult(state) {
      state.bookingValues[2].value = 0;
      state.bookingValues[3].value = 0;
    },
  },
});

export default searchSlice;
export const searchActions = searchSlice.actions;
